# Generated by Django 3.1.2 on 2022-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Problem_statement', models.CharField(max_length=100000)),
                ('Author', models.CharField(max_length=1000)),
                ('Number_of_submissions', models.IntegerField()),
                ('Number_of_accepted', models.IntegerField()),
                ('Test_cases', models.CharField(max_length=1000000000)),
                ('Example_test_cases', models.CharField(max_length=10000)),
                ('Solution', models.CharField(max_length=1000000)),
            ],
        ),
    ]
