# Generated by Django 3.1.2 on 2022-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='Example_test_cases',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problems',
            name='Problem_statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problems',
            name='Solution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problems',
            name='Test_cases',
            field=models.TextField(),
        ),
    ]
