# Generated by Django 3.1.2 on 2022-06-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_app', '0002_auto_20220626_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problems',
            name='Number_of_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problems',
            name='Number_of_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_problemsetter', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_app.problems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
