# Generated by Django 3.1.2 on 2022-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0003_auto_20220626_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
