# Generated by Django 3.1.2 on 2022-06-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0004_auto_20220626_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='user',
        ),
    ]
