# Generated by Django 3.1.2 on 2022-06-27 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_app', '0005_remove_submissions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='problem',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.problems'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
