# Generated by Django 3.1.2 on 2022-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0007_auto_20220627_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
